[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 1
libs = ["../../node_modules", "../../../mud"]
src = "src"
test = "test"
out = "out"
extra_output_files = ["abi", "evm.bytecode"]
fs_permissions = [{ access = "read", path = "./" }]
gas_limit = 60000000

[profile.lattice-testnet]
eth_rpc_url = "https://follower.testnet2-chain.linfra.xyz"

[profile.redstone]
eth_rpc_url = "https://redstone-holesky-testnet.rpc.thirdweb.com/"

[profile.redstone-holesky]
eth_rpc_url = "https://ethereum-holesky.publicnode.com"

[profile.goerli]
eth_rpc_url = "https://eth-goerli.g.alchemy.com/v2/xxxx/"

[profile.sepolia]
eth_rpc_url = "https://eth-sepolia.g.alchemy.com/v2/xxxx/"